spring:
  config:
    import: optional:file:.env.properties
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5432/core-service-db
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
    show-sql: true
    open-in-view: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

property:
  app:
    staticUrl: ${STATIC_URL:http://localhost:8080}
    yandexClientId: ${YANDEX_CLIENT_ID}
    yandexClientSecret: ${YANDEX_CLIENT_SECRET}
    jwtCookieName: app-jwt
    jwtRefreshCookieName: app-jwt-refresh
    jwtSecret: ${JWT_SECRET:==========secret=phrase=string=example=============}
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 18000000